version: '3'
services:
  db:
    image: postgres:14.5
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
