name: CI

on:
  push:
    branchs:
      - main
  workflow_dispatch:

jobs:
#  test:
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v3
#        with:
#          go-version: '1.17'
#      - name: Test
#        run: |
#          cd hello-world
#          go test

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
#    needs: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket ${{ secrets.AMAZON_S3_BUCKET }}
