version = 0.1

[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "techboost-05-echo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1chmzs3joeuh3"
s3_prefix = "techboost-05-echo"
region = "ap-northeast-1"
confirm_changeset = true
disable_rollback = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
