version = 0.1

[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "techboost-05-evacuation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1chmzs3joeuh3"
s3_prefix = "techboost-05-evacuation"
region = "ap-northeast-1"
confirm_changeset = false
disable_rollback = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
